In [650]:
%load_ext autoreload
%autoreload 

import sys
import numpy as np

if '../' not in sys.path: sys.path.append('../')
print(sys.path)

from src.model import Learn, Setup, Predict, Model
from src.memory_pool import Pool

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
['/home/bukkacha/Desktop/Inductive bias/notebooks', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/home/bukkacha/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.10/dist-packages', '../']


In [651]:
nscalars = 4
nvectors = 4
nfeatures = 2
pool = Pool(nscalars, nvectors, nfeatures)

In [652]:
model = Model(nscalars, nvectors, nfeatures)

In [655]:
for _ in range(5):
  model.mutate(pool)

In [656]:
model


    Model structure:

      Setup: 
    	scalars=[3.6572568  4.85940797 0.18200422 3.16136483], 
    	vectors=[[-2.276283139127111, 6.165704560692994], [8.426648764042884, 3.129502526653864], [1.6188414126525537, 8.967973444404777], [-4.688700662704228, -7.0022216636039]]
    
      Learn: 
      	magnitute(s3)=s0
	subtraction(s2, s0)=s1
	
      Predict: 
      	matmul(v0, v2)=s0
	matmul(v2, v2)=s2
	magnitute(s2)=s1
	
    

In [497]:
learn = Learn()
predict = Predict()

In [501]:
pool.set_scalars(np.random.randn(nscalars))
pool.set_vectors(np.random.randn(nvectors, nfeatures))
pool


Pool(
scalars=[-0.06663429 -0.63025022  0.47294012  1.62496043], 
vectors=
[[-0.2838817   0.53330234]
 [-0.38258335  0.002105  ]
 [-0.69081695 -0.86591891]
 [ 2.09156466 -0.95144452]]
)

In [502]:
for _ in range(10):
  predict.mutate(pool)
  predict.eval_func(pool)

In [503]:
pool

Pool(
scalars=[ 0.10973101 -0.2560966   0.47294012 -0.14636559], 
vectors=
[[ 1.0490484   0.52909234]
 [-0.38258335  0.002105  ]
 [ 0.69081695  0.86591891]
 [ 0.38258335  0.002105  ]]
)

In [504]:
predict._functions, predict._args

([3, 2, 1, 3, 1, 1],
 [{'arg_indices': array([1, 0]),
   'arg_type': 1,
   'return_idx': array([0]),
   'return_type': 1},
  {'arg_indices': array([1, 3]),
   'arg_type': 1,
   'return_idx': array([3]),
   'return_type': 0},
  {'arg_indices': array([3]),
   'arg_type': 1,
   'return_idx': array([3]),
   'return_type': 1},
  {'arg_indices': array([3, 0]),
   'arg_type': 0,
   'return_idx': array([1]),
   'return_type': 0},
  {'arg_indices': array([0]),
   'arg_type': 1,
   'return_idx': array([0]),
   'return_type': 1},
  {'arg_indices': array([1]),
   'arg_type': 1,
   'return_idx': array([3]),
   'return_type': 1}])

In [505]:
np.zeros(4)

array([0., 0., 0., 0.])